#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

files="bashrc vimrc tmux.conf irbrc inputrc i3 i3status.conf terminator"

for file in $files; do
	if [ -e ~/.$file ]; then
		mkdir -p ~/dotfiles-old
		mv ~/.$file ~/dotfiles-old
	fi
	ln -s $dir/$file ~/.$file
done
