#!/bin/bash

# usages:
# ./install
# ./install term
# ./install gui

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

termfiles="bashrc vimrc tmux.conf irbrc inputrc"
guifiles="i3 i3status.conf terminator"

if [ $# -eq 0 ]; then
	files="$termfiles $guifiles"
elif [ "$1" == "term" ]; then
	files="$termfiles"
elif [ "$1" == "gui" ]; then
	files="$guifiles"
fi

for file in $files; do
	if [ -e ~/.$file ]; then
		mkdir -p ~/dotfiles-old
		mv ~/.$file ~/dotfiles-old
	fi
	ln -s $dir/$file ~/.$file
done
